apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: contacts
  name: contacts
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: contacts
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.network: "true"
        io.kompose.service: contacts
    spec:
      containers:
        - image: gtato/sharelatex-contacts
          name: contacts
          ports:
            - containerPort: 3036
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/mongodb
              name: contacts-claim0
      restartPolicy: Always
      volumes:
        - name: contacts-claim0
          persistentVolumeClaim:
            claimName: contacts-claim0
status: {}

