apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: docstore
  name: docstore
spec:
  ports:
    - name: "3016"
      port: 3016
      targetPort: 3016
  selector:
    io.kompose.service: docstore
status:
  loadBalancer: {}

