apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: document-updater
  name: document-updater
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: document-updater
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.network/default: "true"
        io.kompose.service: document-updater
    spec:
      containers:
        - image: gtato/sharelatex-document-updater
          name: document-updater
          ports:
            - containerPort: 3003
          resources:
            requests:
              cpu: 2500m
            limits:
              cpu: 2500m
      restartPolicy: Always
status: {}

