apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: filestore
  name: filestore
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: filestore
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.network: "true"
        io.kompose.service: filestore
    spec:
      containers:
        - image: gtato/sharelatex-filestore
          name: filestore
          ports:
            - containerPort: 3009
          resources:
            requests:
              cpu: 2500m
            limits:
              cpu: 2500m
          volumeMounts:
            - mountPath: /app/data
              name: filestore-claim0
      restartPolicy: Always
      volumes:
        - name: filestore-claim0
          persistentVolumeClaim:
            claimName: filestore-claim0
status: {}

