apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: real-time
  name: real-time
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: real-time
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.network/default: "true"
        io.kompose.service: real-time
    spec:
      containers:
        - image: gtato/sharelatex-real-time
          name: real-time
          ports:
            - containerPort: 3026
          resources: {}
      restartPolicy: Always
status: {}

