apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: spelling
  name: spelling
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: spelling
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.network: "true"
        io.kompose.service: spelling
    spec:
      containers:
        - image: gtato/sharelatex-spelling
          name: spelling
          ports:
            - containerPort: 3005
          resources:
            requests:
              cpu: 2500m
            limits:
              cpu: 2500m
          volumeMounts:
            - mountPath: /var/lib/mongodb
              name: spelling-claim0
      restartPolicy: Always
      volumes:
        - name: spelling-claim0
          persistentVolumeClaim:
            claimName: spelling-claim0
status: {}

