apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: tags
  name: tags
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: tags
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.network: "true"
        io.kompose.service: tags
    spec:
      containers:
        - image: gtato/sharelatex-tags
          name: tags
          ports:
            - containerPort: 3012
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/mongodb
              name: tags-claim0
      restartPolicy: Always
      volumes:
        - name: tags-claim0
          persistentVolumeClaim:
            claimName: tags-claim0
status: {}

