apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: web
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: web
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.network/default: "true"
        io.kompose.service: web
    spec:
      containers:
        - args:
            - bash
            - app.sh
          env:
            - name: SHARELATEX_APP_NAME
              value: MicroSharedLatex
            - name: SHARELATEX_CONFIG
              value: /etc/sharelatex/settings.coffee
            - name: SHARELATEX_REAL_TIME_URL
              value: http://155.98.38.125:30911
            - name: SHARELATEX_REDIS_HOST
              value: redis
            - name: SHARELATEX_SESSION_SECRET
              value: secret-please-change
            - name: SHARELATEX_SITE_URL
              value: http://localhost:8080/
          image: kapila1/sharelatex-web
          name: web
          ports:
            - containerPort: 80
            - containerPort: 3000
          resources: {}
          securityContext:
            privileged: true
      restartPolicy: Always
status: {}

